### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jpessin-BU** [YangLab/CLEAR#1]
When installing as per instructions, the installer runs without error, however, there seem to be some underlying linking/module placing and finding issues.
(I've had the same issue with multiple python3 installations, for reproducibly here it is in conda on Linux)

``` conda env -n clear python==3.6.5
conda activate clear
conda install circexplorer2 -c bioconda
git clone https://github.com/YangLab/CLEAR.git
cd CLEAR
python ./setup.py install 
```
. . . 
verbose checking creating copying
. . . 
```
Adding CLEAR 1.0.0 to easy-install.pth file
Installing circ_quant script to /usr2/collab/pessinj/.conda/envs/clear/bin
Installing clear_quant script to /usr2/collab/pessinj/.conda/envs/clear/bin
Installed /usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/CLEAR-1.0.0-py3.6.egg
Processing dependencies for CLEAR==1.0.0
Searching for pybedtools==0.8.0
Best match: pybedtools 0.8.0
Adding pybedtools 0.8.0 to easy-install.pth file
Using /usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages
Searching for pysam==0.15.3
Best match: pysam 0.15.3 
Adding pysam 0.15.3 to easy-install.pth file
Using /usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages 
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file
Using /usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages
Finished processing dependencies for CLEAR==1.0.0
```

clear_quant and circ_quant are now in the path

```
(clear) [pessinj@scc2 clear]$ which clear_quant
~/.conda/envs/clear/bin/clear_quant 
(clear) [pessinj@scc2 clear]$ which circ_quant
~/.conda/envs/clear/bin/circ_quant
```

But clear_quant cannot find circ_quant

`
(clear) [pessinj@scc2 CLEAR]$ clear_quant -h                                                                                                                                                                        Traceback (most recent call last):                                                                                                                                                                                    File "/usr2/collab/pessinj/.conda/envs/clear/bin/clear_quant", line 11, in                                                                                                                                    load_entry_point('CLEAR==1.0.0', 'console_scripts', 'clear_quant')()                                                                                                                                              File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 489, in load_entry_point                                                                                                                                                                                            return get_distribution(dist).load_entry_point(group, name)                                                                                                                                                       File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 2843, in load_entry_point                                                                                                                                                                                           return ep.load()                                                                                                                                                                                                  File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 2434, in load                                                                                                                                                                                                       return self.resolve()                                                                                                                                                                                             File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 2440, in resolve                                                                                                                                                                                                    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                                             File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/CLEAR-1.0.0-py3.6.egg/src/run                                                                                                            .py", line 11, in                                                                                                                                                                                           ModuleNotFoundError: No module named 'circ_quant'
`

and circ_quant cannot find spReads

`
(clear) [pessinj@scc2 CLEAR]$ circ_quant -h                                                                                                                                                                         Traceback (most recent call last):                                                                                                                                                                                    File "/usr2/collab/pessinj/.conda/envs/clear/bin/circ_quant", line 11, in                                                                                                                                     load_entry_point('CLEAR==1.0.0', 'console_scripts', 'circ_quant')()                                                                                                                                               File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 489, in load_entry_point                                                                                                                                                                                            return get_distribution(dist).load_entry_point(group, name)                                                                                                                                                       File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 2843, in load_entry_point                                                                                                                                                                                           return ep.load()                                                                                                                                                                                                  File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 2434, in load                                                                                                                                                                                                       return self.resolve()                                                                                                                                                                                             File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/pkg_resources/__init__.py", l                                                                                                            ine 2440, in resolve                                                                                                                                                                                                    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                                             File "/usr2/collab/pessinj/.conda/envs/clear/lib/python3.6/site-packages/CLEAR-1.0.0-py3.6.egg/src/cir                                                                                                            c_quant.py", line 19, in                                                                                                                                                                                    ModuleNotFoundError: No module named 'spReads'
`

spReads is in the git repo 

```
(clear) [pessinj@scc2 CLEAR]$ find $PWD -name spRead* 
/usr2/collab/pessinj/CLEAR/build/lib/src/spReads.py 
/usr2/collab/pessinj/CLEAR/src/spReads.py
```

but some quick use of find does not turn it up in the conda-python space

```
(clear) [pessinj@scc2 CLEAR]$ cd ~/.conda/envs/clear/
(clear) [pessinj@scc2 clear]$ find $PWD -name spRead*
(clear) [pessinj@scc2 clear]$ find $PWD -name clear*
/usr2/collab/pessinj/.conda/envs/clear
/usr2/collab/pessinj/.conda/envs/clear/bin/clear
/usr2/collab/pessinj/.conda/envs/clear/bin/clear_quant
(clear) [pessinj@scc2 clear]$ find $PWD -name circ*
/usr2/collab/pessinj/.conda/envs/clear/bin/circ_quant
/usr2/collab/pessinj/.conda/envs/clear/conda-meta/circexplorer2-2.3.6-py_0.json
```

**Comment by shameem356** [comment]
I am also facing same issue. could you please look into the issue.
