### ISSUE TITLE
Feature Request: Calculate FPBlinear for all genes

### ISSUE THREAD

**Issue by bounlu** [YangLab/CLEAR#12]
Hi,

I think it will be very useful to obtain FPBlinear values in a sample for all the linear RNAs from the ref file, even though there is no circRNA generated from them. The FPBcirc values for those could be set to 0 in the output, hence CIRCscore will be also 0, but FPBlinear will be non-zero as long as the gene is expressed.

Best.

---

Have you tried [CSI NGS Portal](https://csibioinfo.nus.edu.sg/csingsportal) yet?

**Comment by xingma** [comment]
Hi,

There is a temporary folder in the same directory of "quant.txt". In the temporary folder, the "gene_hpb.txt" file contains FPBlinear values for all linear RNAs. Thanks.

Best.
