### ISSUE TITLE
Issue when using clear_quant

### ISSUE THREAD

**Issue by JunmingH** [YangLab/CLEAR#2]
Hi

I met some issue when I try to run clear_quant function
"[2019-08-29 12:58:42] Mapping left_kept_reads to genome hg19 with Bowtie
        [FAILED]
Error running bowtie:
Error while flushing and closing output
terminate called after throwing an instance of 'int'"

I check this error in the website which said I am run out of storage. But that would not possible since I am using server.

**Comment by Scathacheng** [comment]
Hi,
I am also running clear_quant. I want to ask which version of bowtie did you use. I run the clear_quant but it report the bug that bowtie index returned non-zero exit status 1.
Do you have similar bug? Thanks!

**Comment by JunmingH** [comment]
Hi @Scathacheng I am not running clear-quant finally. Since there have too much error. STAR is also a good tools for alignment
