### ISSUE TITLE
STAR bam files?

### ISSUE THREAD

**Issue by zwardnz** [YangLab/CLEAR#5]
Not an issue but I have used circexplorer2 for my analyses and would now like to upgrade.
I tried running previous analysis starting from circexplorer2 output and bam files mapped with STAR (circ_quant).
I don't get any expression of cognate linear RNA reads.

Am I able to do the analysis with STAR bam files???

**Comment by xingma** [comment]
Yes. CLEAR can be used to analyzed with STAR bam. For your problem, I think one possible reason is that the chromosome names are different between STAR bam file and the gene annotation file.
