### ISSUE TITLE
Tophat2, Bowtie, Samtools compatibility problems

### ISSUE THREAD

**Issue by battlerb** [YangLab/CLEAR#6]
Hi, there

I'm appreciate your hard-working for keeping upgrade CIRCexplorer pipeline. When I found your latest version CIRCexplorer3/CLEAR start using Hisat2 for the very first alignment, I cannot wait to try it. 

However, I got a same problem as I met when I use CIRCexplorer2. Tophat2 (version 2.1.0) kept sending me error like :'Error running bowtie: Error while flushing and closing output'. Then I realized it was another compatibility problem with tophat2 and bowtie.  
![image](https://user-images.githubusercontent.com/50813246/80933999-a487f200-8df8-11ea-9b76-6514e8518f14.png)

Then I tried to find solution across biostar and github. Finally I found that your answer in another issue which is bowtie (v0.12.9), tophat2 (v2.0.12) works very well (https://github.com/YangLab/CLEAR/issues/3). I installed those older version software and tried to run it again, then it raise an error seems like tophat2 do not know my Samtools version...... (Probably my Samtools v1.10 version is too high.)
![image](https://user-images.githubusercontent.com/50813246/80933974-83270600-8df8-11ea-9b3e-0b71f5c78f80.png)

Is there any possible using other aligner like STAR to align un-mapped reads? Or would you please share your software version. I'm really appreciate for your help.

Regards

**Comment by xingma** [comment]
Hi battlerb, STAR also can be used to align unmapped reads. In addition, samtools (v0.1.19-44428cd), bowtie (v0.12.9), tophat2 (v2.0.12) and hisat2 (v2.0.5) works well. You may try these versions. Thanks.
